# Featured clients for CMS features proposal page
# Logo files are stored in payslip/static/payslip/clients/

FEATURED_CLIENTS = [
    {"name": "Aalim Muhammed Salegh College of Engineering", "logo": "aalim.png"},
    {"name": "Annai Mira College of Engineering and Technology", "logo": "annai mera.png"},
    {"name": "Coimbatore Institute of Engineering and Technology", "logo": "ciet.png"},
    {"name": "Dhanalakshmi Srinivasan University", "logo": "dsc.png"},
    {"name": "E.G.S. Pillay Engineering College", "logo": "egs.png"},
    {"name": "GRG Educational Institutions", "logo": "grg.png"},
    {"name": "G.T.N. Arts College", "logo": "gtn.png"},
    {"name": "Jansons School of Business", "logo": "JSB-website-baner-1 1.png"},
    {"name": "Kristu Jayanti University", "logo": "kirstu janti university.png"},
    {"name": "Karur Kongu College of Arts and Science", "logo": "kocas.png"},
    {"name": "Kovai Kalaimagal College of Arts and Science", "logo": "kovai-kalaimagal-college.png"},
    {"name": "KSG College of Arts and Science – Coimbatore", "logo": "ksg.png"},
    {"name": "Dr. Mahalingam College of Engineering and Technology", "logo": "mcet.png"},
    {"name": "Nandha College of Engineering", "logo": "nandha.png"},
    {"name": "PSG College of Arts & Science", "logo": "psg cas.png"},
    {"name": "PSG Institute of Technology and Applied Research", "logo": "psgitarlogo 1.png"},
    {"name": "SAN International College of Arts and Science", "logo": "san.png"},
    {"name": "Sankara Arts and Science College", "logo": "sankara.png"},
    {"name": "Sri Ramakrishna College of Arts & Science for Women", "logo": "SNR.png 1.png"},
    {"name": "Shri Nehru Maha Vidyalaya College of Arts & Science", "logo": "snmv-logo-ad-page-scaled 1.png"},
    {"name": "Sakthi Polytechnic College", "logo": "SPCLOGO 1.png"},
    {"name": "Sri Ramakrishna Central School", "logo": "srcs.png"},
    {"name": "Sri Sai Ranganathan Engineering College", "logo": "ssr.png"},
    {"name": "Vanavarayar Institute of Agriculture", "logo": "vanavarayar.png"},
    {"name": "Vethathiri Maharishi Smart School", "logo": "vethathiri.png"},
    {"name": "Vidyaa Vikas College of Engineering and Technology", "logo": "vidya vikas.png"},
    {"name": "Vivekananda Global Academy", "logo": "Viveganandha-Global-Academy.png"},
    {"name": "Vinayaka Mission's Kirupananda Variyar Medical College", "logo": "VMKVMCH-.png"},
]
