"""
Seed data for the Aveon Income module - GENERATED verbatim from
Client_Wise_Student_Count_Finalised.ods. Amount fields are strings to be
converted to Decimal at load time (never floats).
Loaded by: python manage.py seed_income --commit
"""

SEED_ROWS = [{'client': 'EGSP',
  'academic_year': '2024-2025',
  'student_count': 10114,
  'rate': '0.00',
  'one_time_payment': '0',
  'override_amounts': True,
  'taxable_value': '720339.00',
  'gst_amount': '129661.02',
  'net_amount': '850000.02',
  'previous_pending': '250000.00',
  'received': '1000000.00',
  'engineer': 'Balachandhar',
  'invoice_status': '',
  'remarks': 'Per Year 850000 | Sheet showed received 850000.00; opening set to 1000000.00 to '
             'match sheet balance',
  'agreement_status': '',
  'is_active': True},
 {'client': 'EGSP',
  'academic_year': '2025-2026',
  'student_count': 11000,
  'rate': '0.00',
  'one_time_payment': '0',
  'override_amounts': True,
  'taxable_value': '720339.00',
  'gst_amount': '129661.02',
  'net_amount': '850000.02',
  'previous_pending': '0',
  'received': '850000.00',
  'engineer': '',
  'invoice_status': 'PROFORMA',
  'remarks': 'Mail Sent to Concerned IE',
  'agreement_status': '',
  'is_active': True},
 {'client': 'VIA',
  'academic_year': '2025-2026',
  'student_count': 250,
  'rate': '185.00',
  'one_time_payment': '300000.00',
  'override_amounts': True,
  'taxable_value': '46250.00',
  'gst_amount': '62325.00',
  'net_amount': '408575.00',
  'previous_pending': '0',
  'received': '150000.00',
  'engineer': 'Balachandhar',
  'invoice_status': 'ALREADY_SENT',
  'remarks': 'One time Payment advance received : 1,50,000/-',
  'agreement_status': '',
  'is_active': True},
 {'client': 'GTN Arts',
  'academic_year': '2024-2025',
  'student_count': 4673,
  'rate': '150.00',
  'one_time_payment': '0',
  'override_amounts': True,
  'taxable_value': None,
  'gst_amount': '0',
  'net_amount': '600000.00',
  'previous_pending': '0',
  'received': '600000.00',
  'engineer': 'Balachandhar',
  'invoice_status': '',
  'remarks': 'Finalised 600000',
  'agreement_status': 'Live till 2029',
  'is_active': True},
 {'client': 'GTN Arts',
  'academic_year': '2025-2026',
  'student_count': 4913,
  'rate': '127.12',
  'one_time_payment': '0',
  'override_amounts': True,
  'taxable_value': '624540.56',
  'gst_amount': '112417.30',
  'net_amount': '736957.86',
  'previous_pending': '0',
  'received': '0',
  'engineer': '',
  'invoice_status': 'ALREADY_SENT',
  'remarks': 'Mail Sent to Concerned IE',
  'agreement_status': '',
  'is_active': True},
 {'client': 'GTN Engineering',
  'academic_year': '2025-2026',
  'student_count': 169,
  'rate': '127.12',
  'one_time_payment': '0',
  'override_amounts': True,
  'taxable_value': '21483.28',
  'gst_amount': '3866.99',
  'net_amount': '25350.27',
  'previous_pending': '0',
  'received': '0',
  'engineer': 'Balachandhar',
  'invoice_status': 'ALREADY_SENT',
  'remarks': 'Mail Sent to Concerned IE',
  'agreement_status': '',
  'is_active': True},
 {'client': 'Cluster',
  'academic_year': '2024-2025',
  'student_count': 161,
  'rate': None,
  'one_time_payment': '0',
  'override_amounts': True,
  'taxable_value': '80000.00',
  'gst_amount': '14400.00',
  'net_amount': '94400.00',
  'previous_pending': '0',
  'received': '0',
  'engineer': 'Kalai',
  'invoice_status': '',
  'remarks': "Payment will be credited beyond Jan 2 and don't call them.",
  'agreement_status': '',
  'is_active': True},
 {'client': 'Cluster',
  'academic_year': '2025-2026',
  'student_count': 168,
  'rate': None,
  'one_time_payment': '0',
  'override_amounts': True,
  'taxable_value': '80000.00',
  'gst_amount': '14400.00',
  'net_amount': '94400.00',
  'previous_pending': '0',
  'received': '0',
  'engineer': '',
  'invoice_status': 'ALREADY_SENT',
  'remarks': 'Mail Sent to Concerned IE',
  'agreement_status': '',
  'is_active': True},
 {'client': 'SNMV',
  'academic_year': '2024-2025',
  'student_count': 3002,
  'rate': '150.00',
  'one_time_payment': '0',
  'override_amounts': True,
  'taxable_value': '450300.00',
  'gst_amount': '81054.00',
  'net_amount': '531354.00',
  'previous_pending': '0',
  'received': '531354.00',
  'engineer': 'Mullai',
  'invoice_status': '',
  'remarks': '',
  'agreement_status': '',
  'is_active': True},
 {'client': 'SNMV',
  'academic_year': '2025-2026',
  'student_count': 3197,
  'rate': '250.00',
  'one_time_payment': '0',
  'override_amounts': True,
  'taxable_value': '799250.00',
  'gst_amount': '143865.00',
  'net_amount': '943115.00',
  'previous_pending': '0',
  'received': '0',
  'engineer': '',
  'invoice_status': '',
  'remarks': 'Rate needs to be finalised (Agreement) | Agreement Pending',
  'agreement_status': '',
  'is_active': True},
 {'client': 'SPC',
  'academic_year': '2024-2025',
  'student_count': 933,
  'rate': '150.00',
  'one_time_payment': '0',
  'override_amounts': True,
  'taxable_value': '139950.00',
  'gst_amount': '25191.00',
  'net_amount': '165141.00',
  'previous_pending': '0',
  'received': '128748.00',
  'engineer': 'Mullai',
  'invoice_status': '',
  'remarks': 'Should send an reminder mail',
  'agreement_status': '',
  'is_active': True},
 {'client': 'SPC',
  'academic_year': '2025-2026',
  'student_count': 979,
  'rate': '250.00',
  'one_time_payment': '0',
  'override_amounts': True,
  'taxable_value': '244750.00',
  'gst_amount': '44055.00',
  'net_amount': '288805.00',
  'previous_pending': '0',
  'received': '0',
  'engineer': '',
  'invoice_status': '',
  'remarks': 'Rate needs to be finalised (Agreement) | Agreement Pending',
  'agreement_status': '',
  'is_active': True},
 {'client': 'SANSAC',
  'academic_year': '2024-2025',
  'student_count': 1203,
  'rate': '150.00',
  'one_time_payment': '0',
  'override_amounts': True,
  'taxable_value': '180450.00',
  'gst_amount': '32481.00',
  'net_amount': '212931.00',
  'previous_pending': '0',
  'received': '212931.00',
  'engineer': 'Mullai',
  'invoice_status': '',
  'remarks': 'Should send an reminder mail',
  'agreement_status': '',
  'is_active': True},
 {'client': 'SANSAC',
  'academic_year': '2025-2026',
  'student_count': 1643,
  'rate': '350.00',
  'one_time_payment': '0',
  'override_amounts': True,
  'taxable_value': '575050.00',
  'gst_amount': '103509.00',
  'net_amount': '678559.00',
  'previous_pending': '0',
  'received': '0',
  'engineer': '',
  'invoice_status': '',
  'remarks': 'Rate needs to be finalised (Agreement) | Agreement Pending',
  'agreement_status': '',
  'is_active': True},
 {'client': 'JSB',
  'academic_year': '2025-2026',
  'student_count': 190,
  'rate': None,
  'one_time_payment': '0',
  'override_amounts': True,
  'taxable_value': '350000.00',
  'gst_amount': '63000.00',
  'net_amount': '413000.00',
  'previous_pending': '0',
  'received': '0',
  'engineer': 'Mullai',
  'invoice_status': 'ALREADY_SENT',
  'remarks': 'Per year 350000',
  'agreement_status': '',
  'is_active': True},
 {'client': 'SANICAS : MBA - 33, ARTS - 406',
  'academic_year': '2025-2026',
  'student_count': 439,
  'rate': '300.00',
  'one_time_payment': '177000.00',
  'override_amounts': True,
  'taxable_value': '131700.00',
  'gst_amount': '23706.00',
  'net_amount': '332406.00',
  'previous_pending': '0',
  'received': '0',
  'engineer': 'Naveen Prasath',
  'invoice_status': 'PROFORMA',
  'remarks': 'Mail Sent to Concerned IE',
  'agreement_status': '',
  'is_active': True},
 {'client': 'TSA (Aided)',
  'academic_year': '2024-2025',
  'student_count': 326,
  'rate': '200.00',
  'one_time_payment': '0',
  'override_amounts': True,
  'taxable_value': '65200.00',
  'gst_amount': '11736.00',
  'net_amount': '76936.00',
  'previous_pending': '0',
  'received': '76936.00',
  'engineer': 'Mullai',
  'invoice_status': '',
  'remarks': 'Should followup with Vijaykumar Sir | Sheet showed received 76396.00; opening set to '
             '76936.00 to match sheet balance',
  'agreement_status': '',
  'is_active': True},
 {'client': 'TSA (SF)',
  'academic_year': '2024-2025',
  'student_count': 598,
  'rate': '200.00',
  'one_time_payment': '0',
  'override_amounts': True,
  'taxable_value': '119600.00',
  'gst_amount': '21528.00',
  'net_amount': '141128.00',
  'previous_pending': '0',
  'received': '141128.00',
  'engineer': 'Mullai',
  'invoice_status': '',
  'remarks': 'Should followup with Vijaykumar Sir',
  'agreement_status': '',
  'is_active': True},
 {'client': 'MCET',
  'academic_year': '2024-2025',
  'student_count': 4229,
  'rate': '87.50',
  'one_time_payment': '300000.00',
  'override_amounts': True,
  'taxable_value': '370037.50',
  'gst_amount': '66606.75',
  'net_amount': '736644.25',
  'previous_pending': '118000.00',
  'received': '881644.00',
  'engineer': 'Selladurai',
  'invoice_status': 'PROFORMA',
  'remarks': 'Invoice Sent | Net includes one-time payment',
  'agreement_status': '',
  'is_active': True},
 {'client': 'MCET',
  'academic_year': '2025-2026',
  'student_count': 4596,
  'rate': '185.00',
  'one_time_payment': '0',
  'override_amounts': True,
  'taxable_value': '850260.00',
  'gst_amount': '153046.80',
  'net_amount': '1003306.80',
  'previous_pending': '0',
  'received': '501653.80',
  'engineer': '',
  'invoice_status': 'PROFORMA',
  'remarks': 'Proforma Invoice raised for ODD Sem alone | Invoice Sent',
  'agreement_status': '',
  'is_active': True},
 {'client': 'AMC',
  'academic_year': '2024-2025',
  'student_count': None,
  'rate': None,
  'one_time_payment': '0',
  'override_amounts': True,
  'taxable_value': None,
  'gst_amount': '0',
  'net_amount': '35000.00',
  'previous_pending': '0',
  'received': '35000.00',
  'engineer': 'Selladurai',
  'invoice_status': '',
  'remarks': 'Per year 35000/- only',
  'agreement_status': '',
  'is_active': True},
 {'client': 'AMC',
  'academic_year': '2025-2026',
  'student_count': None,
  'rate': None,
  'one_time_payment': '0',
  'override_amounts': True,
  'taxable_value': None,
  'gst_amount': '0',
  'net_amount': '35000.00',
  'previous_pending': '0',
  'received': '0',
  'engineer': '',
  'invoice_status': 'NOT_NEEDED',
  'remarks': 'Payment will be credited within January month.',
  'agreement_status': '',
  'is_active': True},
 {'client': 'SRCW',
  'academic_year': '2024-2025',
  'student_count': 1632,
  'rate': '198.00',
  'one_time_payment': '0',
  'override_amounts': True,
  'taxable_value': '323136.00',
  'gst_amount': '58164.48',
  'net_amount': '381300.48',
  'previous_pending': '0',
  'received': '381300.48',
  'engineer': 'Selladurai',
  'invoice_status': '',
  'remarks': 'Engineers: Selladurai & Naveen R',
  'agreement_status': '',
  'is_active': True},
 {'client': 'SRCW',
  'academic_year': '2025-2026',
  'student_count': 1484,
  'rate': '168.00',
  'one_time_payment': '0',
  'override_amounts': True,
  'taxable_value': '249312.00',
  'gst_amount': '44876.16',
  'net_amount': '294188.16',
  'previous_pending': '0',
  'received': '294188.16',
  'engineer': 'Naveen R',
  'invoice_status': 'PROFORMA',
  'remarks': '',
  'agreement_status': '',
  'is_active': True},
 {'client': 'KIC (or) EBET',
  'academic_year': '2024-2025',
  'student_count': 1078,
  'rate': '150.00',
  'one_time_payment': '0',
  'override_amounts': True,
  'taxable_value': '161700.00',
  'gst_amount': '29106.00',
  'net_amount': '190806.00',
  'previous_pending': '0',
  'received': '190806.00',
  'engineer': 'Selladurai',
  'invoice_status': '',
  'remarks': 'Tax Invoice sent via mail',
  'agreement_status': '',
  'is_active': True},
 {'client': 'KIC (or) EBET',
  'academic_year': '2025-2026',
  'student_count': 1632,
  'rate': '150.00',
  'one_time_payment': '0',
  'override_amounts': True,
  'taxable_value': '244800.00',
  'gst_amount': '44064.00',
  'net_amount': '288864.00',
  'previous_pending': '0',
  'received': '0',
  'engineer': '',
  'invoice_status': 'PROFORMA',
  'remarks': '',
  'agreement_status': '',
  'is_active': True},
 {'client': 'KJC',
  'academic_year': '2024-2025',
  'student_count': None,
  'rate': None,
  'one_time_payment': '0',
  'override_amounts': True,
  'taxable_value': None,
  'gst_amount': '0',
  'net_amount': '0',
  'previous_pending': '0',
  'received': '0',
  'engineer': 'Selladurai',
  'invoice_status': '',
  'remarks': 'One-time payment noted as: Around 3 Lakhs | Received noted as: Around 3 Lakhs',
  'agreement_status': '',
  'is_active': True},
 {'client': 'KJC',
  'academic_year': '2025-2026',
  'student_count': None,
  'rate': None,
  'one_time_payment': '0',
  'override_amounts': True,
  'taxable_value': None,
  'gst_amount': '0',
  'net_amount': '0',
  'previous_pending': '0',
  'received': '0',
  'engineer': '',
  'invoice_status': '',
  'remarks': 'Client Discontinued',
  'agreement_status': '',
  'is_active': False},
 {'client': 'NPT',
  'academic_year': '2024-2025',
  'student_count': 1107,
  'rate': None,
  'one_time_payment': '300000.00',
  'override_amounts': True,
  'taxable_value': None,
  'gst_amount': '0',
  'net_amount': '300000.00',
  'previous_pending': '0',
  'received': '300000.00',
  'engineer': 'Suresh',
  'invoice_status': '',
  'remarks': 'Not yet started | Invoice Sent | Net includes one-time payment',
  'agreement_status': '',
  'is_active': True},
 {'client': 'NPT',
  'academic_year': '2025-2026',
  'student_count': 1641,
  'rate': '185.00',
  'one_time_payment': '0',
  'override_amounts': True,
  'taxable_value': '303585.00',
  'gst_amount': '54645.30',
  'net_amount': '358230.30',
  'previous_pending': '0',
  'received': '151792.30',
  'engineer': '',
  'invoice_status': '',
  'remarks': 'Madam should speak with College | Invoice Sent',
  'agreement_status': '',
  'is_active': True},
 {'client': 'SSREC',
  'academic_year': '2024-2025',
  'student_count': 874,
  'rate': '200.00',
  'one_time_payment': '0',
  'override_amounts': True,
  'taxable_value': '174800.00',
  'gst_amount': '31464.00',
  'net_amount': '206264.00',
  'previous_pending': '0',
  'received': '206264.00',
  'engineer': 'Suresh',
  'invoice_status': '',
  'remarks': '',
  'agreement_status': '',
  'is_active': True},
 {'client': 'SSREC',
  'academic_year': '2025-2026',
  'student_count': 1025,
  'rate': '200.00',
  'one_time_payment': '0',
  'override_amounts': True,
  'taxable_value': '205000.00',
  'gst_amount': '36900.00',
  'net_amount': '241900.00',
  'previous_pending': '0',
  'received': '120950.00',
  'engineer': '',
  'invoice_status': 'PROFORMA',
  'remarks': 'Part Payment Received & Tax Invoice sent via mail',
  'agreement_status': '',
  'is_active': True},
 {'client': 'Group : CIET - 1906, KKCAS - 608, SOA - 43, CMAT - 60',
  'academic_year': '2024-2025',
  'student_count': 2617,
  'rate': '200.00',
  'one_time_payment': '0',
  'override_amounts': True,
  'taxable_value': '523400.00',
  'gst_amount': '94212.00',
  'net_amount': '617612.00',
  'previous_pending': '0',
  'received': '600000.00',
  'engineer': 'Kariyappan',
  'invoice_status': '',
  'remarks': '',
  'agreement_status': '',
  'is_active': True},
 {'client': 'Group : CIET - 1906, KKCAS - 608, SOA - 43, CMAT - 60',
  'academic_year': '2025-2026',
  'student_count': 2617,
  'rate': '200.00',
  'one_time_payment': '0',
  'override_amounts': True,
  'taxable_value': '523400.00',
  'gst_amount': '94212.00',
  'net_amount': '617612.00',
  'previous_pending': '0',
  'received': '600000.00',
  'engineer': '',
  'invoice_status': 'PROFORMA',
  'remarks': 'Mail Sent to Concerned IE',
  'agreement_status': '',
  'is_active': True},
 {'client': 'PSG iTech',
  'academic_year': '2025-2026',
  'student_count': 1431,
  'rate': None,
  'one_time_payment': '0',
  'override_amounts': True,
  'taxable_value': '275000.00',
  'gst_amount': '49500.00',
  'net_amount': '324500.00',
  'previous_pending': '0',
  'received': '0',
  'engineer': 'Kariyappan',
  'invoice_status': 'WAITING',
  'remarks': '',
  'agreement_status': '',
  'is_active': True},
 {'client': 'PSG CAS',
  'academic_year': '2025-2026',
  'student_count': 3000,
  'rate': None,
  'one_time_payment': '0',
  'override_amounts': True,
  'taxable_value': '275000.00',
  'gst_amount': '49500.00',
  'net_amount': '324500.00',
  'previous_pending': '0',
  'received': '0',
  'engineer': '',
  'invoice_status': 'WAITING',
  'remarks': 'Student count not finalised',
  'agreement_status': '',
  'is_active': True},
 {'client': 'GRG',
  'academic_year': '2025-2026',
  'student_count': 2092,
  'rate': '100.00',
  'one_time_payment': '0',
  'override_amounts': True,
  'taxable_value': '209200.00',
  'gst_amount': '37656.00',
  'net_amount': '246856.00',
  'previous_pending': '0',
  'received': '90000.00',
  'engineer': 'Kariyappan',
  'invoice_status': 'ALREADY_SENT',
  'remarks': 'Mail Sent to Concerned IE & 90000/- has been paid as advance.',
  'agreement_status': '',
  'is_active': True},
 {'client': 'JKKM',
  'academic_year': '2025-2026',
  'student_count': 500,
  'rate': None,
  'one_time_payment': '0',
  'override_amounts': True,
  'taxable_value': None,
  'gst_amount': '0',
  'net_amount': '0.00',
  'previous_pending': '0',
  'received': '0',
  'engineer': 'Kariyappan',
  'invoice_status': '',
  'remarks': 'Client Discontinued',
  'agreement_status': '',
  'is_active': False},
 {'client': 'Vethathiri Maharishi School',
  'academic_year': '2024-2025',
  'student_count': 2200,
  'rate': '0.00',
  'one_time_payment': '50000.00',
  'override_amounts': True,
  'taxable_value': None,
  'gst_amount': '0',
  'net_amount': '50000.00',
  'previous_pending': '0',
  'received': '50000.00',
  'engineer': 'Naveen R',
  'invoice_status': '',
  'remarks': 'Net includes one-time payment',
  'agreement_status': '',
  'is_active': True},
 {'client': 'Vethathiri Maharishi School',
  'academic_year': '2025-2026',
  'student_count': 2200,
  'rate': None,
  'one_time_payment': '0',
  'override_amounts': True,
  'taxable_value': None,
  'gst_amount': '0',
  'net_amount': '0',
  'previous_pending': '0',
  'received': '0',
  'engineer': 'Naveen R',
  'invoice_status': '',
  'remarks': 'Rate needs to be finalised (Agreement) | Only AMC should be collected - Madam should '
             'decide and Naveen R should implement some of the modules in the school.',
  'agreement_status': '',
  'is_active': True},
 {'client': 'SNR School',
  'academic_year': '2025-2026',
  'student_count': None,
  'rate': None,
  'one_time_payment': '0',
  'override_amounts': True,
  'taxable_value': None,
  'gst_amount': '0',
  'net_amount': '0',
  'previous_pending': '0',
  'received': '0',
  'engineer': 'Naveen R',
  'invoice_status': '',
  'remarks': 'Rate needs to be finalised (Agreement)',
  'agreement_status': '',
  'is_active': True},
 {'client': 'Vivekananda School',
  'academic_year': '2025-2026',
  'student_count': 120,
  'rate': None,
  'one_time_payment': '0',
  'override_amounts': True,
  'taxable_value': None,
  'gst_amount': '0',
  'net_amount': '0',
  'previous_pending': '0',
  'received': '0',
  'engineer': 'Naveen R',
  'invoice_status': '',
  'remarks': 'Rate needs to be finalised (Agreement) | 25000/- advance',
  'agreement_status': '',
  'is_active': True},
 {'client': 'Vinayaka Mission College',
  'academic_year': '2025-2026',
  'student_count': None,
  'rate': None,
  'one_time_payment': '0',
  'override_amounts': True,
  'taxable_value': None,
  'gst_amount': '0',
  'net_amount': '0',
  'previous_pending': '0',
  'received': '0',
  'engineer': 'Naveen R',
  'invoice_status': '',
  'remarks': 'Rate needs to be finalised (Agreement)',
  'agreement_status': '',
  'is_active': True},
 {'client': 'Sri Sakthi Polytechnic',
  'academic_year': '2025-2026',
  'student_count': None,
  'rate': None,
  'one_time_payment': '0',
  'override_amounts': True,
  'taxable_value': None,
  'gst_amount': '0',
  'net_amount': '0',
  'previous_pending': '0',
  'received': '0',
  'engineer': 'Naveen R',
  'invoice_status': '',
  'remarks': 'Rate needs to be finalised (Agreement)',
  'agreement_status': '',
  'is_active': True},
 {'client': 'KSG',
  'academic_year': '2025-2026',
  'student_count': None,
  'rate': None,
  'one_time_payment': '125000.00',
  'override_amounts': True,
  'taxable_value': None,
  'gst_amount': '0',
  'net_amount': '125000.00',
  'previous_pending': '0',
  'received': '125000.00',
  'engineer': 'Naveen Prasath',
  'invoice_status': '',
  'remarks': 'Net includes one-time payment',
  'agreement_status': '',
  'is_active': True},
 {'client': 'Kongu CAS',
  'academic_year': '2025-2026',
  'student_count': 1230,
  'rate': '250.00',
  'one_time_payment': '0',
  'override_amounts': True,
  'taxable_value': '307500.00',
  'gst_amount': '55350.00',
  'net_amount': '362850.00',
  'previous_pending': '0',
  'received': '50000.00',
  'engineer': 'Dharun',
  'invoice_status': '',
  'remarks': 'Still no Invoice generated',
  'agreement_status': 'Live till 2029',
  'is_active': True}]
