from django.urls import include, path
from django.views.generic import RedirectView

from . import views_implementation, views_income, views_payroll, views_people, views_proposal_history, views_team
from .views import (
    cms_feature_list,
    company_profile,
    download_file,
    experience_certificate,
    landing,
    offer_letter,
    preview_pdf,
    profile_logo,
    signup,
    travel_expense,
    proposal_quotation,
)

urlpatterns = [
    path("", landing, name="landing"),
    path("accounts/signup/", signup, name="signup"),
    path("accounts/", include("django.contrib.auth.urls")),
    path("profile/", company_profile, name="company_profile"),
    path("profile/logo/", profile_logo, name="profile_logo"),
    # --- Team management (org admins) ---
    path("team/", views_team.team, name="team"),
    path("team/add/", views_team.team_add_member, name="team_add_member"),
    path("team/<int:user_id>/toggle/", views_team.team_toggle_member, name="team_toggle_member"),
    # --- People registry (candidates & interns) ---
    path("people/", views_people.people_list, name="people_list"),
    path("people/new/", views_people.person_create, name="person_create"),
    path("people/<int:pk>/", views_people.person_detail, name="person_detail"),
    path("people/<int:pk>/convert/", views_people.person_convert, name="person_convert"),
    path("offer-letter/", offer_letter, name="offer_letter"),
    path("experience-certificate/", experience_certificate, name="experience_certificate"),
    path("travel-expense/", travel_expense, name="travel_expense"),
    path("payslip/", RedirectView.as_view(pattern_name="payroll_run_list", permanent=False), name="upload_payslips"),
    path("proposal-quotation/", proposal_quotation, name="proposal_quotation"),
    path("proposal-quotation/cms-features/", cms_feature_list, name="cms_feature_list"),
    path("proposal-quotation/history/", views_proposal_history.proposal_history, name="proposal_history"),
    path("proposal-quotation/history/<int:pk>/", views_proposal_history.proposal_record, name="proposal_record"),
    path("preview/<str:token>/", preview_pdf, name="preview_pdf"),
    path("download/<str:token>/", download_file, name="download_file"),
    # --- Income module (staff-only) ---
    path("income/", views_income.income_dashboard, name="income_dashboard"),
    path("income/analytics/", views_income.income_analytics, name="income_analytics"),
    path("income/clients/", views_income.income_client_list, name="income_client_list"),
    path("income/clients/new/", views_income.income_client_create, name="income_client_create"),
    path("income/clients/<int:pk>/", views_income.income_client_detail, name="income_client_detail"),
    path("income/clients/<int:pk>/edit/", views_income.income_client_edit, name="income_client_edit"),
    path("income/clients/<int:pk>/toggle-active/", views_income.income_client_toggle_active, name="income_client_toggle_active"),
    path("income/clients/<int:pk>/billing/new/", views_income.income_billing_create, name="income_billing_create"),
    path("income/billing/<int:pk>/edit/", views_income.income_billing_edit, name="income_billing_edit"),
    path("income/billing/<int:pk>/payments/add/", views_income.income_payment_add, name="income_payment_add"),
    path("income/payments/<int:pk>/delete/", views_income.income_payment_delete, name="income_payment_delete"),
    path("income/implementation/", views_implementation.implementation_dashboard, name="implementation_dashboard"),
    path("income/clients/<int:pk>/implementation/", views_implementation.client_implementation, name="client_implementation"),
    path("income/export.xlsx", views_income.income_export, name="income_export"),
    path("income/import/", views_income.income_import, name="income_import"),
    # --- Payroll module ---
    path("payroll/settings/", views_payroll.payroll_settings, name="payroll_settings"),
    path("payroll/structure/", views_payroll.salary_structure, name="salary_structure"),
    path("payroll/entries/<int:pk>/breakdown/", views_payroll.payroll_entry_breakdown, name="payroll_entry_breakdown"),
    path("payroll/employees/", views_payroll.employee_list, name="employee_list"),
    path("payroll/employees/export/", views_payroll.employee_export, name="employee_export"),
    path("payroll/employees/new/", views_payroll.employee_create, name="employee_create"),
    path("payroll/employees/<int:pk>/", views_payroll.employee_detail, name="employee_detail"),
    path("payroll/employees/<int:pk>/photo/", views_payroll.employee_photo, name="employee_photo"),
    path("payroll/runs/", views_payroll.payroll_run_list, name="payroll_run_list"),
    path("payroll/runs/new/", views_payroll.payroll_run_create, name="payroll_run_create"),
    path("payroll/runs/<int:pk>/", views_payroll.payroll_run_detail, name="payroll_run_detail"),
    path("payroll/runs/<int:pk>/finalize/", views_payroll.payroll_run_finalize, name="payroll_run_finalize"),
    path("payroll/runs/<int:pk>/recalculate/", views_payroll.payroll_run_recalculate, name="payroll_run_recalculate"),
    path("payroll/runs/<int:pk>/reopen/", views_payroll.payroll_run_reopen, name="payroll_run_reopen"),
    path("payroll/runs/<int:pk>/generate-payslips/", views_payroll.payroll_generate_payslips, name="payroll_generate_payslips"),
    path("payroll/runs/<int:pk>/export.xlsx", views_payroll.payroll_register_export, name="payroll_register_export"),
    path("payroll/entries/<int:pk>/<str:action>/", views_payroll.payroll_entry_pdf, name="payroll_entry_pdf"),
]

