# Generated by Django 4.2.29 on 2026-07-14 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import payslip.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedFile',
            fields=[
                ('token', models.CharField(default=payslip.models._new_token, max_length=32, primary_key=True, serialize=False)),
                ('content', models.BinaryField()),
                ('content_type', models.CharField(max_length=100)),
                ('filename', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, default='', max_length=200)),
                ('tagline', models.CharField(blank=True, default='', max_length=200)),
                ('address', models.TextField(blank=True, default='')),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('country', models.CharField(blank=True, default='India', max_length=100)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('website', models.CharField(blank=True, default='', max_length=200)),
                ('jurisdiction', models.CharField(blank=True, default='', max_length=200)),
                ('logo', models.BinaryField(blank=True, editable=True, null=True)),
                ('logo_content_type', models.CharField(blank=True, default='', max_length=50)),
                ('brand_primary', models.CharField(default='#1565C0', max_length=7)),
                ('brand_accent', models.CharField(default='#2E7D32', max_length=7)),
                ('signatory_name', models.CharField(blank=True, default='', max_length=200)),
                ('signatory_designation', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
