# Generated by Django 4.2.29 on 2026-07-14 17:59

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payslip', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientBilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^\\d{4}-\\d{4}$', 'Use the format 2024-2025.')])),
                ('year_start', models.PositiveSmallIntegerField(db_index=True, default=0, editable=False)),
                ('student_count', models.PositiveIntegerField(blank=True, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('one_time_payment', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('override_amounts', models.BooleanField(default=False)),
                ('taxable_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('net_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('previous_pending', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('engineer', models.CharField(blank=True, choices=[('Balachandhar', 'Balachandhar'), ('Kalai', 'Kalai'), ('Mullai', 'Mullai'), ('Naveen Prasath', 'Naveen Prasath'), ('Selladurai', 'Selladurai'), ('Naveen R', 'Naveen R'), ('Suresh', 'Suresh'), ('Kariyappan', 'Kariyappan'), ('Dharun', 'Dharun')], default='', max_length=50)),
                ('invoice_status', models.CharField(blank=True, choices=[('PROFORMA', 'Proforma invoice generated'), ('ALREADY_SENT', 'Proforma invoice sent'), ('TAX_SENT', 'Tax invoice sent'), ('NOT_NEEDED', 'Invoice not needed'), ('WAITING', 'Waiting')], default='', max_length=20)),
                ('remarks', models.TextField(blank=True, default='')),
                ('next_followup_date', models.DateField(blank=True, db_index=True, null=True)),
                ('followup_note', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['client__name', 'year_start'],
            },
        ),
        migrations.CreateModel(
            name='IncomeClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('agreement_status', models.CharField(blank=True, default='', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('received_on', models.DateField(blank=True, null=True)),
                ('mode', models.CharField(blank=True, default='', max_length=50)),
                ('note', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('billing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payslip.clientbilling')),
            ],
            options={
                'ordering': ['-received_on', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='clientbilling',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billings', to='payslip.incomeclient'),
        ),
        migrations.AlterUniqueTogether(
            name='clientbilling',
            unique_together={('client', 'academic_year')},
        ),
    ]
