# Generated by Django 4.2.29 on 2026-07-14 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payslip', '0002_income_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientbilling',
            name='engineer',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
