# Generated by Django 4.2.29 on 2026-07-14 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payslip', '0003_engineer_free_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientOnboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('ONBOARDING', 'Onboarding'), ('IMPLEMENTATION', 'Implementation'), ('LIVE', 'Live'), ('ON_HOLD', 'On hold'), ('DISCONTINUED', 'Discontinued')], default='ONBOARDING', max_length=20)),
                ('contact_person', models.CharField(blank=True, default='', max_length=200)),
                ('contact_designation', models.CharField(blank=True, default='', max_length=200)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=30)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('institution_type', models.CharField(blank=True, choices=[('COLLEGE', 'College'), ('SCHOOL', 'School'), ('UNIVERSITY', 'University'), ('POLYTECHNIC', 'Polytechnic'), ('OTHER', 'Other')], default='', max_length=20)),
                ('address', models.TextField(blank=True, default='')),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('student_strength', models.PositiveIntegerField(blank=True, null=True)),
                ('onboarded_on', models.DateField(blank=True, null=True)),
                ('go_live_date', models.DateField(blank=True, null=True)),
                ('engineer', models.CharField(blank=True, default='', max_length=50)),
                ('po_received', models.BooleanField(default=False)),
                ('po_number', models.CharField(blank=True, default='', max_length=100)),
                ('po_date', models.DateField(blank=True, null=True)),
                ('agreement_signed', models.BooleanField(default=False)),
                ('agreement_years', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('agreement_start', models.DateField(blank=True, null=True)),
                ('agreement_end', models.DateField(blank=True, null=True)),
                ('reminder_days', models.PositiveSmallIntegerField(default=90)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding', to='payslip.incomeclient')),
            ],
        ),
        migrations.CreateModel(
            name='FeatureStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not started'), ('IN_PROGRESS', 'In progress'), ('TESTING', 'Testing'), ('LIVE', 'Live'), ('ON_HOLD', 'On hold'), ('NA', 'N.A.')], default='NOT_STARTED', max_length=20)),
                ('engineer', models.CharField(blank=True, default='', max_length=50)),
                ('started_on', models.DateField(blank=True, null=True)),
                ('completed_on', models.DateField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, default='', max_length=300)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='payslip.incomeclient')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('client', 'name')},
            },
        ),
    ]
