# Generated by Django 4.2.29 on 2026-07-15 00:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payslip', '0004_implementation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, default='', max_length=200)),
                ('tagline', models.CharField(blank=True, default='', max_length=200)),
                ('address', models.TextField(blank=True, default='')),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('country', models.CharField(blank=True, default='India', max_length=100)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('website', models.CharField(blank=True, default='', max_length=200)),
                ('jurisdiction', models.CharField(blank=True, default='', max_length=200)),
                ('logo', models.BinaryField(blank=True, editable=True, null=True)),
                ('logo_content_type', models.CharField(blank=True, default='', max_length=50)),
                ('brand_primary', models.CharField(default='#1565C0', max_length=7)),
                ('brand_accent', models.CharField(default='#2E7D32', max_length=7)),
                ('signatory_name', models.CharField(blank=True, default='', max_length=200)),
                ('signatory_designation', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('MEMBER', 'Member')], default='MEMBER', max_length=10)),
                ('can_payslips', models.BooleanField(default=True, verbose_name='Payslips')),
                ('can_offer_letters', models.BooleanField(default=True, verbose_name='Offer Letters')),
                ('can_experience_certificates', models.BooleanField(default=True, verbose_name='Experience Certificates')),
                ('can_travel_expense', models.BooleanField(default=True, verbose_name='Travel Expense')),
                ('can_proposals', models.BooleanField(default=True, verbose_name='Proposals')),
                ('can_income', models.BooleanField(default=False, verbose_name='Income')),
                ('can_implementation', models.BooleanField(default=False, verbose_name='Implementation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='payslip.organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
