# Generated by Django 4.2.29 on 2026-07-15 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payslip', '0006_copy_profiles_to_orgs'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomeclient',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='income_clients', to='payslip.organization'),
        ),
        migrations.AlterField(
            model_name='incomeclient',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='incomeclient',
            unique_together={('organization', 'name')},
        ),
    ]
