# Generated by Django 4.2.29 on 2026-07-15 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payslip', '0008_assign_income_org'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(db_index=True, max_length=200)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('form_data', models.JSONField(blank=True, default=dict)),
                ('html', models.TextField()),
                ('selection_label', models.CharField(blank=True, default='', max_length=200)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='payslip.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('organization', 'client_name', 'revision')},
            },
        ),
    ]
