# Generated by Django 4.2.29 on 2026-07-18 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payslip', '0010_org_cleanup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('CANDIDATE', 'Candidate / Employee'), ('INTERN', 'Internship Student')], max_length=12)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('title', models.CharField(blank=True, default='', max_length=10)),
                ('gender', models.CharField(blank=True, default='', max_length=10)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('address', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('employee_no', models.CharField(blank=True, default='', max_length=100)),
                ('designation', models.CharField(blank=True, default='', max_length=200)),
                ('join_date', models.DateField(blank=True, null=True)),
                ('leaving_date', models.DateField(blank=True, null=True)),
                ('roll_number', models.CharField(blank=True, default='', max_length=100)),
                ('course', models.CharField(blank=True, default='', max_length=200)),
                ('college_name', models.CharField(blank=True, default='', max_length=200)),
                ('college_address', models.TextField(blank=True, default='')),
                ('internship_role', models.CharField(blank=True, default='', max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people', to='payslip.organization')),
            ],
            options={
                'verbose_name_plural': 'people',
                'ordering': ['name'],
                'unique_together': {('organization', 'kind', 'name')},
            },
        ),
        migrations.AddField(
            model_name='membership',
            name='can_people',
            field=models.BooleanField(default=True, verbose_name='People'),
        ),
        migrations.CreateModel(
            name='PersonDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('INTERNSHIP_OFFER', 'Internship Offer Letter'), ('APPOINTMENT', 'Appointment Order'), ('EMPLOYMENT_OFFER', 'Offer Letter'), ('EXPERIENCE_EMPLOYEE', 'Experience Letter'), ('EXPERIENCE_INTERNSHIP', 'Internship Experience Certificate')], max_length=25)),
                ('form_data', models.JSONField(blank=True, default=dict)),
                ('pdf', models.BinaryField()),
                ('pdf_plain', models.BinaryField(blank=True, null=True)),
                ('filename', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_documents', to='payslip.organization')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='payslip.person')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
