# Generated by Django 4.2.29 on 2026-07-20 06:19

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payslip', '0011_people'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(max_length=30)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('designation', models.CharField(blank=True, default='', max_length=200)),
                ('doj', models.DateField(blank=True, null=True)),
                ('relieving_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('current_monthly_package', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('bank_name', models.CharField(blank=True, default='', max_length=200)),
                ('bank_account_number', models.CharField(blank=True, default='', max_length=50)),
                ('ifsc_code', models.CharField(blank=True, default='', max_length=20)),
                ('pan_number', models.CharField(blank=True, default='', max_length=20)),
                ('pf_number', models.CharField(blank=True, default='', max_length=50)),
                ('pf_uan', models.CharField(blank=True, default='', max_length=50)),
                ('esi_number', models.CharField(blank=True, default='', max_length=50)),
                ('is_esi_eligible', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='payslip.organization')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profile', to='payslip.person')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('organization', 'employee_code')},
            },
        ),
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('FINALIZED', 'Finalized')], default='DRAFT', max_length=10)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('finalized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_runs', to='payslip.organization')),
            ],
            options={
                'ordering': ['-period'],
                'unique_together': {('organization', 'period')},
            },
        ),
        migrations.AddField(
            model_name='membership',
            name='can_payroll',
            field=models.BooleanField(default=False, verbose_name='Payroll'),
        ),
        migrations.CreateModel(
            name='PayrollSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_percent_of_package', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=5)),
                ('da_percent_of_basic', models.DecimalField(decimal_places=2, default=Decimal('45.00'), max_digits=5)),
                ('hra_percent_of_basic', models.DecimalField(decimal_places=2, default=Decimal('25.00'), max_digits=5)),
                ('transport_percent_of_basic', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5)),
                ('food_percent_of_basic', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5)),
                ('esi_employee_percent', models.DecimalField(decimal_places=2, default=Decimal('0.75'), max_digits=5)),
                ('esi_employer_percent', models.DecimalField(decimal_places=2, default=Decimal('3.25'), max_digits=5)),
                ('esi_wage_ceiling', models.DecimalField(decimal_places=2, default=Decimal('21000.00'), max_digits=10)),
                ('pf_employee_percent', models.DecimalField(decimal_places=2, default=Decimal('12.00'), max_digits=5)),
                ('pf_employer_percent', models.DecimalField(decimal_places=2, default=Decimal('12.00'), max_digits=5)),
                ('pf_wage_cap', models.DecimalField(decimal_places=2, default=Decimal('15000.00'), max_digits=10)),
                ('pf_wage_factor', models.DecimalField(decimal_places=2, default=Decimal('60.00'), max_digits=5)),
                ('pf_employer_matches_employee', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_settings', to='payslip.organization')),
            ],
        ),
        migrations.CreateModel(
            name='PayslipEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_package', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_working_days', models.PositiveSmallIntegerField()),
                ('cl_credit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('emp_leave_days', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('lop_days', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('present_days', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('pay_days', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('internet_allowance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('salary_arrear_allowance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('salary_advance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('tds', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('basic', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('da', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('hra', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('transport_allowance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('food_allowance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('gross_salary', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('is_esi_eligible', models.BooleanField(default=False)),
                ('esi_employee', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('esi_employer', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('pf_employee', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('pf_employer', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('net_payable', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('remarks', models.TextField(blank=True, default='')),
                ('pdf', models.BinaryField(blank=True, null=True)),
                ('pdf_plain', models.BinaryField(blank=True, null=True)),
                ('pdf_generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslip_entries', to='payslip.employee')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslip_entries', to='payslip.organization')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='payslip.payrollrun')),
            ],
            options={
                'ordering': ['employee__name'],
                'unique_together': {('run', 'employee')},
            },
        ),
    ]
