# Generated by Django 4.2.29 on 2026-07-20 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payslip', '0012_payroll'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_pf_applicable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payslipentry',
            name='is_pf_applicable',
            field=models.BooleanField(default=False),
        ),
    ]
