# Generated by Django 4.2.29 on 2026-07-20 07:41

from django.db import migrations


def carry_payslips_right_into_payroll(apps, schema_editor):
    """The old standalone Payslip tool is gone; Payroll absorbs it. No one
    who could already generate payslips should lose that ability, so every
    membership that had can_payslips=True gets can_payroll=True too."""
    Membership = apps.get_model('payslip', 'Membership')
    Membership.objects.filter(can_payslips=True, can_payroll=False).update(can_payroll=True)


class Migration(migrations.Migration):

    dependencies = [
        ('payslip', '0013_payroll_pf_applicable'),
    ]

    operations = [
        migrations.RunPython(carry_payslips_right_into_payroll, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='membership',
            name='can_payslips',
        ),
    ]
