# Generated by Django 4.2.29 on 2026-07-21 09:23

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payslip', '0014_payslips_merge_into_payroll'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='Default structure', max_length=120)),
                ('effective_from', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_structures', to='payslip.organization')),
            ],
            options={
                'ordering': ['-effective_from'],
                'unique_together': {('organization', 'effective_from')},
            },
        ),
        migrations.AddField(
            model_name='payslipentry',
            name='ctc',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='payslipentry',
            name='employer_contributions',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.CreateModel(
            name='StructureChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=120)),
                ('detail', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structure_change_logs', to='payslip.organization')),
                ('structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_logs', to='payslip.salarystructure')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalaryComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('EARNING', 'Earning'), ('DEDUCTION', 'Employee Deduction'), ('EMPLOYER_CONTRIB', 'Employer Contribution'), ('INFO', 'Informational')], default='EARNING', max_length=20)),
                ('calc_method', models.CharField(choices=[('FIXED', 'Fixed amount'), ('PERCENT_OF', 'Percentage of a component'), ('FORMULA', 'Formula expression')], default='FORMULA', max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('percent', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=7)),
                ('base_code', models.CharField(blank=True, default='', max_length=40)),
                ('formula', models.TextField(blank=True, default='')),
                ('rounding', models.CharField(choices=[('HALF_UP', 'Round (half up)'), ('CEILING', 'Round up'), ('FLOOR', 'Round down'), ('NONE', 'No rounding')], default='HALF_UP', max_length=10)),
                ('decimals', models.PositiveSmallIntegerField(default=2)),
                ('include_in_gross', models.BooleanField(default=True)),
                ('is_esi_base', models.BooleanField(default=False)),
                ('is_pf_base', models.BooleanField(default=False)),
                ('is_taxable', models.BooleanField(default=False)),
                ('statutory_type', models.CharField(choices=[('NONE', 'None'), ('PF', 'Provident Fund'), ('ESI', 'ESI'), ('PT', 'Professional Tax'), ('TDS', 'TDS')], default='NONE', max_length=8)),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='payslip.salarystructure')),
            ],
            options={
                'ordering': ['sequence', 'id'],
                'unique_together': {('structure', 'code')},
            },
        ),
        migrations.CreateModel(
            name='PayslipComponentAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('source_expr', models.TextField(blank=True, default='')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_amounts', to='payslip.payslipentry')),
            ],
            options={
                'ordering': ['sequence', 'id'],
                'unique_together': {('entry', 'code')},
            },
        ),
    ]
