# Generated by Django 4.2.29 on 2026-07-22 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payslip', '0016_employee_hr_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='agreement_years',
        ),
        migrations.AddField(
            model_name='employee',
            name='agreement_sign_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='agreement_signed',
            field=models.BooleanField(default=False),
        ),
    ]
